Script started on 2016年03月09日 (週三) 22時19分20秒
]0;F74046357@2015cpp: ~[01;32mF74046357@2015cpp[00m:[01;34m~[00m$ whoamilp[K[K;pe[Kwd
F74046357
/home/F74046357
]0;F74046357@2015cpp: ~[01;32mF74046357@2015cpp[00m:[01;34m~[00m$ git config -l
user.email=minmin260558@gmail.com
user.name=minmin260558
]0;F74046357@2015cpp: ~[01;32mF74046357@2015cpp[00m:[01;34m~[00m$ git clone http://githun[Kn[Kb.com/minmin260559[K8/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 9, done.[K
remote: Compressing objects:  16% (1/6)   [Kremote: Compressing objects:  33% (2/6)   [Kremote: Compressing objects:  50% (3/6)   [Kremote: Compressing objects:  66% (4/6)   [Kremote: Compressing objects:  83% (5/6)   [Kremote: Compressing objects: 100% (6/6)   [Kremote: Compressing objects: 100% (6/6), done.[K
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0[K
Unpacking objects:  11% (1/9)   Unpacking objects:  22% (2/9)   Unpacking objects:  33% (3/9)   Unpacking objects:  44% (4/9)   Unpacking objects:  55% (5/9)   Unpacking objects:  66% (6/9)   Unpacking objects:  77% (7/9)   Unpacking objects:  88% (8/9)   Unpacking objects: 100% (9/9)   Unpacking objects: 100% (9/9), done.
]0;F74046357@2015cpp: ~[01;32mF74046357@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月09日 (週三) 22時20分23秒
